name: Bun executable release

on:
  pull_request:
  branches: ["main"]

jobs:
  build:
    name: Build executable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun build ./src/index.ts --compile --outfile=gptcli
